apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-microservices
  labels:
    app.kubernetes.io/component: immich-microservices
    app.kubernetes.io/name: immich
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: immich-microservices
      app.kubernetes.io/name: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/component: immich-microservices
        app.kubernetes.io/name: immich
    spec:
      # Prevent config interference
      enableServiceLinks: false
      containers:
        - name: immich-microservices
          image: ghcr.io/immich-app/immich-server:latest

          env:
            - name: IMMICH_WORKERS_EXCLUDE
              value: "api"
          envFrom:
            - configMapRef:
                name: immich-env
            - secretRef:
                name: immich-credentials

          volumeMounts:
            - name: library
              mountPath: /usr/src/app/upload

          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 125Mi
