apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-alert
  labels:
    app: pi-alert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-alert
  template:
    metadata:
      labels:
        app: pi-alert
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      
      containers:
        - name: pi-alert
          image: jokobsk/pi.alert:sha-fcfac14
          imagePullPolicy: IfNotPresent

          env:
            - name: TZ
              value: Europe/Berlin

          volumeMounts:
            - name: config
              mountPath: /home/pi/pialert/config
            - name: database
              mountPath: /home/pi/pialert/db

          ports:
            - name: ui
              containerPort: 20211
              protocol: TCP
          
          resources:
            limits:
              memory: "125Mi"
              cpu: "100m"
    