apiVersion: apps/v1
kind: Deployment
metadata:
  name: openspeedtest
  labels:
    app.kubernetes.io/name: openspeedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openspeedtest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openspeedtest
    spec:
      dnsPolicy: ClusterFirst
      hostNetwork: false
      containers:
        - name: openspeedtest
          image: "openspeedtest/latest:v2.0.4"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: 20M
              cpu: 20m
            limits:
              memory: 100M
              cpu: 100m
          ports:
            - name: http
              containerPort: 3000  
              protocol: TCP
            - name: https
              containerPort: 3001
              protocol: TCP
          env:
          - name: TZ
            value: "Europe/Berlin"