apiVersion: v1
kind: Service
metadata:
  name: openspeedtest
  labels:
    app.kubernetes.io/name: openspeedtest
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
    - name: http
      port: 443
      targetPort: 3001
      protocol: TCP
  selector:
    app.kubernetes.io/name: openspeedtest