apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app.kubernetes.io/name: homeassistant

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: homeassistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homeassistant
    spec:
      dnsPolicy: ClusterFirst
      hostNetwork: false
      
      containers:
        - name: homeassistant
          image: homeassistant/home-assistant:2022.4.1
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: 1Gi
              cpu: 400m
            limits:
              memory: 2Gi
              cpu: 1
          volumeMounts:
            - name: data
              mountPath: /config
          env:
            - name: TZ
              value: Europe/Berlin
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
    