apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: homeassistant

  template:
    metadata:
      labels:
        app: homeassistant

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: false
      
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      
      containers:
        - name: homeassistant
          image: homeassistant/home-assistant:2022.4.1
          imagePullPolicy: IfNotPresent
          
          resources:
            limits:
              memory: "2Gi"
              cpu: 1

          volumeMounts:
            - name: data
              mountPath: /config

          env:
            - name: TZ
              value: Europe/Berlin

          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
    