apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant

spec:
  selector:
    app.kubernetes.io/name: home-assistant
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      protocol: TCP
    - name: unicast
      port: 5683
      targetPort: 5683
      protocol: TCP

    # -- Homematic XmlRpc
    - name: xmlrpc
      port: 1999
      targetPort: 1999
      protocol: TCP
    # -- Homematic JsonRpc
    - name: jsonrpc
      port: 8180
      targetPort: 8180
      protocol: TCP
