apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  labels:
    app: homeassistant
  annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.0.0

spec:
  type: LoadBalancer

  ports:
    - name: http
      port: 80
      targetPort: 8123
      protocol: TCP

  selector:
    app: homeassistant