apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: mosquitto

images:
  - name: eclipse-mosquitto
    newTag: 2.0.20
