apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  labels:
    app.kubernetes.io/component: immich-machine-learning
    app.kubernetes.io/name: immich
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: immich-machine-learning
      app.kubernetes.io/name: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/component: immich-machine-learning
        app.kubernetes.io/name: immich
    spec:
      # Prevent config interference
      enableServiceLinks: false
      containers:
        - name: immich-machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:latest
          env:
            - name: TRANSFORMERS_CACHE
              value: /cache
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          volumeMounts:
            - name: cache
              mountPath: /cache
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "2"
              memory: 3Gi
            requests:
              cpu: 500m
              memory: 1.5Gi
      volumes:
        - name: cache
          emptyDir: {}
