apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-broker
  labels:
    app.kubernetes.io/name: rabbitmq-broker
spec:
  type: ClusterIP
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
  selector:
    app.kubernetes.io/name: rabbitmq