apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ui
  labels:
    app.kubernetes.io/name: rabbitmq-ui
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 15672
      protocol: TCP
  selector:
    app.kubernetes.io/name: rabbitmq