apiVersion: apps/v1
kind: Deployment
metadata:
  name: backrest
  labels:
    app.kubernetes.io/name: backrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backrest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backrest
    spec:
      dnsPolicy: ClusterFirst
      hostNetwork: false
      containers:
        - name: backrest
          image: garethgeorge/backrest:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false

          resources:
            limits:
              memory: 128Mi
              cpu: 200m

          volumeMounts:
            - name: data
              mountPath: /data
            - name: cache
              mountPath: /cache

          ports:
            - name: http
              containerPort: 9898
              protocol: TCP

          env:
            - name: TZ
              value: "Europe/Berlin"
            - name: BACKREST_DATA
              value: "/data"
            - name: BACKREST_CONFIG
              value: "/data/config.json"
            - name: XDG_CACHE_HOME
              value: "/cache"

      volumes:
        - name: cache
          emptyDir: {}
