apiVersion: v1
kind: Service
metadata:
  name: backrest
  labels:
    app.kubernetes.io/name: backrest
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: backrest
