apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - ./server
  - ./microservices
  - ./machine-learning

commonLabels:
  app.kubernetes.io/name: immich

images:
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v1.97.0
  - name: ghcr.io/immich-app/immich-server
    newTag: v1.97.0
