apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - ./server
  - ./microservices
  - ./machine-learning

images:
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v1.131.3
  - name: ghcr.io/immich-app/immich-server
    newTag: v1.131.3

configMapGenerator:
  - name: immich-env
    literals:
      - TZ="Europe/Berlin"
      - IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
      - DB_VECTOR_EXTENSION=pgvector
