apiVersion: v1
kind: Service
metadata:
  name: paperless

spec:
  selector:
    app.kubernetes.io/name: paperless
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
