apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-network-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
  