apiVersion: v1
kind: Service
metadata:
  name: mongo-network
  labels:
    app.kubernetes.io/name: mongo-network
    
spec:
  selector:
    app.kubernetes.io/name: mongo-network
  type: ClusterIP
  ports:
    - name: api
      port: 8081
      targetPort: 8081
      protocol: TCP