apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  labels:
    app.kubernetes.io/name: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nodered
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nodered
    spec:
      dnsPolicy: ClusterFirst
      hostNetwork: false
      containers:
        - name: node-red
          image: "nodered/node-red:3.1.9"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false

          resources:
            requests:
              memory: 100M
              cpu: 200m
            limits:
              memory: 500M
              cpu: 1

          volumeMounts:
            - name: data
              mountPath: /data

          ports:
            - name: http
              containerPort: 1880  
              protocol: TCP
              
          env:
          - name: TZ
            value: "Europe/Berlin"
