apiVersion: v1
kind: Service
metadata:
  name: nodered
  labels:
    app.kubernetes.io/name: nodered
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 1880
      protocol: TCP
  selector:
    app.kubernetes.io/name: nodered