apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
data:
  PAPERLESS_URL: "http://paperless:8000"
  PAPERLESS_REDIS: "redis://redis:6379"
  PAPERLESS_DBHOST: "postgres"
  PAPERLESS_DBNAME: "paperless"
  PAPERLESS_DBUSER: "paperless"