apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale
spec:
  selector:
    matchLabels:
      app: tailscale
  replicas: 1
  strategy:
    type: Recreate
  hostNetwork: true
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccountName: tailscale
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:v1.74
          imagePullPolicy: Always

          securityContext:
            capabilities:
              add:
                - NET_ADMIN

          resources:
            requests:
              memory: 200M
              cpu: 100m
            limits:
              memory: 500M
              cpu: 1

          env:
            - name: TS_KUBE_SECRET
              value: "tailscale"
            - name: TS_USERSPACE
              value: "false"
            - name: TS_DEBUG_FIREWALL_MODE
              value: auto
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
                  optional: true

          envFrom:
            - configMapRef:
                name: tailscale-config
