apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale
spec:
  selector:
    matchLabels:
      app: tailscale
  replicas: 1
  hostNetwork: true
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:v1.72.1

          resources:
            requests:
              memory: 200M
              cpu: 100m
            limits:
              memory: 500M
              cpu: 1

          env:
            - name: TS_KUBE_SECRET
              value: "tailscale-state"
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: authkey
