apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  labels: {}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: {}
  template:
    metadata:
      labels: {}
    spec:
      # Prevent config interference
      enableServiceLinks: false
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:latest
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
          args:
            - ./start-server.sh
          env:
            - name: TZ
              value: "Europe/Berlin"
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://immich-machine-learning:3003
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          volumeMounts:
            - name: library
              mountPath: /usr/src/app/upload
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /server-info/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /server-info/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
