apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  labels:
    app.kubernetes.io/component: immich-server
    app.kubernetes.io/name: immich
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: immich-server
      app.kubernetes.io/name: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/component: immich-server
        app.kubernetes.io/name: immich
    spec:
      # Prevent config interference
      enableServiceLinks: false
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:latest
          imagePullPolicy: IfNotPresent

          env:
            - name: IMMICH_WORKERS_INCLUDE
              value: "api"
          envFrom:
            - configMapRef:
                name: immich-env
            - secretRef:
                name: immich-credentials

          ports:
            - name: http
              containerPort: 2283
              protocol: TCP

          volumeMounts:
            - name: library
              mountPath: /usr/src/app/upload

          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 800m
              memory: 512Mi

          # Health checks
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 5
            periodSeconds: 20
            timeoutSeconds: 4

          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 5
            periodSeconds: 20
            timeoutSeconds: 4
