---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  labels: {}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: immich
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
