---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  labels:
    app.kubernetes.io/component: immich-server
    app.kubernetes.io/name: immich
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: immich-server
    app.kubernetes.io/name: immich
  ports:
    - port: 80
      targetPort: 2283
      protocol: TCP
      name: http
