---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  labels: {}
spec:
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: http
      protocol: TCP
      name: http
  selector: {}
