apiVersion: v1
kind: Service
metadata:
  name: frigate
spec:
  ports:
    - name: https
      targetPort: https
      port: 443
    - name: rtmp
      targetPort: rtmp
      port: 1935
    - name: rtsp
      targetPort: rtsp
      port: 8554
  selector:
    app: frigate
