apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  labels:
    app: uptime-kuma

spec:
  type: LoadBalancer

  ports:
    - name: ui
      port: 80
      targetPort: 3001
      protocol: TCP

  selector:
    app: uptime-kuma
