apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  