apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
  labels:
    app.kubernetes.io/name: esphome
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: esphome
  template:
    metadata:
      labels:
        app.kubernetes.io/name: esphome
    spec:
      dnsPolicy: ClusterFirst
      hostNetwork: false
      containers:
        - name: esphome
          image: "esphome/esphome:2024.4.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false

          env:
          - name: ESPHOME_DASHBOARD_USE_PING
            value: "true"

          ports:
            - name: http
              containerPort: 6052  
              protocol: TCP

          volumeMounts:
            - name: config
              mountPath: /config

          resources:
            requests:
              memory: 200M
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 1