apiVersion: v1
kind: Service
metadata:
  name: esphome
  labels:
    app.kubernetes.io/name: esphome
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 6052
      protocol: TCP
  selector:
    app.kubernetes.io/name: esphome