apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  labels:
    app.kubernetes.io/name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zigbee2mqtt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zigbee2mqtt
    spec:
      dnsPolicy: ClusterFirst
      hostNetwork: false
      containers:
        - name: node-red
          image: koenkk/zigbee2mqtt:1.41.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true

          env:
            - name: TZ
              value: Europe/Berlin

          resources:
            requests:
              memory: 100M
              cpu: 200m
            limits:
              memory: 500M
              cpu: 1

          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: udev
              mountPath: /run/udev
            - name: ttyacm
              mountPath: /dev/ttyACM0

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

      volumes:
        - name: udev
          hostPath:
            path: /run/udev
        - name: ttyacm
          hostPath:
            path: /dev/ttyACM0
