apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      dnsPolicy: "ClusterFirst"
      hostNetwork: false
      containers:
        - name: postgres
          image: "postgres:15.2-alpine"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false

          resources:
            limits:
              memory: "1Gi"
              cpu: 1

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data

          ports:
            - name: sql
              containerPort: 5432  
              protocol: TCP

          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_PASSWORD     

      volumes:
        - name: data
          hostPath: 
            path: /var/lib/postgresql/data
            type: DirectoryOrCreate