apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb

spec:
  selector:
    app: influxdb
  ports:
    - name: http
      port: 8086
      targetPort: http
      protocol: TCP
