apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
spec:
  type: LoadBalancer
  ports:
  - name: http
    targetPort: http
    port: 80
  - name: admin
    targetPort: admin
    port: 81
  - name: https
    targetPort: https
    port: 443